# doc: https://github.com/wei/pull#basic-setup
# manua1lly trigger: https://pull.git.ci/process/${fork-user}/BookedScheduler
# pull from: https://github.com/effgarces/BookedScheduler
version: "1"
rules:
  - base: Final
    upstream:  effgarces:Final
    mergeMethod: hardreset
  - base: RC
    upstream: effgarces:RC
    mergeMethod: rebase
